-- MySQL Script generated by MySQL Workbench
-- Wed 15 Mar 2017 02:35:35 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema c2F19B1225
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `c2F19B1225` ;

-- -----------------------------------------------------
-- Schema c2F19B1225
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c2F19B1225` DEFAULT CHARACTER SET utf8 ;
USE `c2F19B1225` ;

-- -----------------------------------------------------
-- Table `c2F19B1225`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`USER` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`USER` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `permissions` ENUM('user', 'staff', 'admin') NOT NULL,
  `inactive` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`USER_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`USER_INFO` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`USER_INFO` (
  `user_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(35) NULL,
  `last_name` VARCHAR(35) NULL,
  `address` VARCHAR(140) NULL,
  `zip` INT(4) UNSIGNED NULL,
  `city` VARCHAR(140) NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` INT(8) NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_USERS_INFO_USERS`
    FOREIGN KEY (`user_id`)
    REFERENCES `c2F19B1225`.`USER` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`PRODUCT` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(512) NULL,
  `price` DOUBLE UNSIGNED NOT NULL DEFAULT 1.0,
  `stock_amount` INT UNSIGNED NOT NULL,
  `owner_user_id` INT UNSIGNED NOT NULL,
  `inactive` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_PRODUCTS_USERS1_idx` (`owner_user_id` ASC),
  CONSTRAINT `fk_PRODUCTS_USERS1`
    FOREIGN KEY (`owner_user_id`)
    REFERENCES `c2F19B1225`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`AUCTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`AUCTION` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`AUCTION` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(512) NULL,
  `start_price` DOUBLE UNSIGNED NOT NULL,
  `owner_user_id` INT UNSIGNED NOT NULL,
  `jump_price` DOUBLE UNSIGNED NOT NULL DEFAULT 0.0,
  `auction_end_date` TIMESTAMP NOT NULL,
  `inactive` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_AUCTIONS_USERS1_idx` (`owner_user_id` ASC),
  CONSTRAINT `fk_AUCTIONS_USERS1`
    FOREIGN KEY (`owner_user_id`)
    REFERENCES `c2F19B1225`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`AUCTION_BID`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`AUCTION_BID` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`AUCTION_BID` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `auction_id` INT UNSIGNED NOT NULL,
  `bid_owner_user_id` INT UNSIGNED NOT NULL,
  `bid_price` DOUBLE UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_AUCTION_BIDS_AUCTIONS1_idx` (`auction_id` ASC),
  INDEX `fk_AUCTION_BIDS_USERS1_idx` (`bid_owner_user_id` ASC),
  CONSTRAINT `fk_AUCTION_BIDS_AUCTIONS1`
    FOREIGN KEY (`auction_id`)
    REFERENCES `c2F19B1225`.`AUCTION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUCTION_BIDS_USERS1`
    FOREIGN KEY (`bid_owner_user_id`)
    REFERENCES `c2F19B1225`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`ORDER` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`ORDER` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_user_id` INT UNSIGNED NULL,
  `created_at` TIMESTAMP NOT NULL,
  `order_status` ENUM('pending', 'packing', 'shipped') NOT NULL,
  `is_paid` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_ORDERS_USERS1_idx` (`customer_user_id` ASC),
  CONSTRAINT `fk_ORDERS_USERS1`
    FOREIGN KEY (`customer_user_id`)
    REFERENCES `c2F19B1225`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`ORDER_PIECE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`ORDER_PIECE` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`ORDER_PIECE` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `auction_id` INT UNSIGNED NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ORDERS_has_USERS_ORDERS1_idx` (`order_id` ASC),
  INDEX `fk_ORDER_PIECE_PRODUCT1_idx` (`product_id` ASC),
  INDEX `fk_ORDER_PIECE_AUCTION1_idx` (`auction_id` ASC),
  CONSTRAINT `fk_ORDERS_has_USERS_ORDERS1`
    FOREIGN KEY (`order_id`)
    REFERENCES `c2F19B1225`.`ORDER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_PIECE_PRODUCT1`
    FOREIGN KEY (`product_id`)
    REFERENCES `c2F19B1225`.`PRODUCT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_PIECE_AUCTION1`
    FOREIGN KEY (`auction_id`)
    REFERENCES `c2F19B1225`.`AUCTION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`USER_SESSION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`USER_SESSION` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`USER_SESSION` (
  `user_id` INT UNSIGNED NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `hash_UNIQUE` (`hash` ASC),
  CONSTRAINT `fk_USER_SESSION_USER1`
    FOREIGN KEY (`user_id`)
    REFERENCES `c2F19B1225`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`AUCTION_IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`AUCTION_IMAGE` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`AUCTION_IMAGE` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `auction_id` INT UNSIGNED NOT NULL,
  `image` TEXT NOT NULL,
  `primary` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_AUCTION_IMAGE_AUCTION1_idx` (`auction_id` ASC),
  CONSTRAINT `fk_AUCTION_IMAGE_AUCTION1`
    FOREIGN KEY (`auction_id`)
    REFERENCES `c2F19B1225`.`AUCTION` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`PRODUCT_IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`PRODUCT_IMAGE` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`PRODUCT_IMAGE` (
  `id` INT NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `image` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PRODUCT_IMAGE_PRODUCT1_idx` (`product_id` ASC),
  CONSTRAINT `fk_PRODUCT_IMAGE_PRODUCT1`
    FOREIGN KEY (`product_id`)
    REFERENCES `c2F19B1225`.`PRODUCT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c2F19B1225`.`USER_HASH`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c2F19B1225`.`USER_HASH` ;

CREATE TABLE IF NOT EXISTS `c2F19B1225`.`USER_HASH` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `remember_identifier` VARCHAR(128) NOT NULL DEFAULT '',
  `remember_token` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_USER_HASH_USER1_idx` (`user_id` ASC),
  CONSTRAINT `fk_USER_HASH_USER1`
    FOREIGN KEY (`user_id`)
    REFERENCES `c2F19B1225`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
